routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);
Route::get('/', function () {
    return view('landingpage.index');
});
/*
Route::get('/', function () {
    return view('custom-auth.login');
});

Route::get('/vouchers',function () {
    return view('custom-views.voucher_master');
});*/
//Auth::routes();
Route::post('/','ContactUsController@index')->name('contact_us');

Route::group(['namespace'=>'Admin','prefix'=>'admin','as','admin.', 'middleware' => ['admin','auth']],function (){
    Route::get('/dashboard','AdminDashboardController@index')->name('dashboard');
    Route::get('/vendor-data','ManageVendorController@data')->name('vendor.data');
    Route::get('/customer-data','ManageCustomerController@data')->name('customer.data');
    Route::get('/account-data','ManageAccountController@data')->name('account.data');
    Route::get('/openingbalance-data','ManageOpeningBalanceController@data')->name('openingbalance.data');
    Route::get('/voucher-data','ManageVoucherController@data')->name('voucher.data');
    Route::post('/ledger-data','LedgerController@data')->name('ledger.data');
    Route::post('/compact-ledger-data','CompactLedgerController@data')->name('compactledger.data');



    //Route::get('/vouchers-data','ManageVoucherController@data')->name('vouchers.data');

    Route::resource('vendors','ManageVendorController');
    Route::resource('customers','ManageCustomerController');
    Route::resource('accounts','ManageAccountController');
    Route::resource('openingbalance','ManageOpeningBalanceController');
    Route::resource('vouchers','ManageVoucherController');
    Route::resource('ledgers','LedgerController');
    Route::resource('compact-ledger','CompactLedgerController');


    Route::post('saveform','ManageVoucherController@saveform')->name('save-form');
    Route::post('delete','ManageVoucherController@delete')->name('delete-data');
    Route::post('showdetail','ManageVoucherController@showdetail')->name('show-detail');

    // Finance Recorders
    Route::resource('managefr', 'ManageFrController');
    Route::get('/fr-data','ManageFrController@data')->name('managefr.data');

});

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/ManageFrController.php
<?php

namespace App\Http\Controllers\Admin;

use App\FinanceRecorder;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DataTables;
use Validator;
use Illuminate\Support\Facades\Auth;

class ManageFrController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $existing = null;
        $financeRecorders = FinanceRecorder::where('user_id','=',Auth::user()->id)->get(); 
        return view('admin.managefr.index',compact('existing','financeRecorders'));
    }

    public function data(){
        $user_id=Auth::user()->id;
       $record = FinanceRecorder::where('user_id',$user_id)->get();
        return DataTables::of($record)
            ->addColumn('action', function ($row){
                return '<a class="btn btn-primary btn-sm" href="'. route('managefr.edit',['fr' => $row->id ]) . '">Edit<div class="ripple-container"></div></a>
                        <button onclick="return Confirm('.$row->id. ')" class="btn btn-danger btn-sm">Delete<div class="ripple-container"></div></button>';
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'amount' => 'required|max:120|min:3',
            'description' => 'required|max:255',
        ]);
      
        if($validator->fails())
        {
            return redirect(route('managefr.index'))->withErrors($validator)->withInput();
        }

        if($request->input('id'))
        {
            $id = $request->input('id');
            $existing = FinanceRecorder::find($id);
            if($existing)
            {
                $existing->amount = $request->input('amount');
                $existing->description = $request->input('description');
                $existing->user_id = Auth::user()->id;//this->id;
                $existing->save();
            }
            return redirect(route('managefr.index'));
        }
        
            
            $existing = new FinanceRecorder();
            if($existing)
            {
                $existing->amount = $request->input('amount');
                $existing->description = $request->input('description');
                $existing->user_id = Auth::user()->id;//this->id;
                $existing->save();
            }
            return redirect(route('managefr.index'));
       
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\FinanceRecorder  $financeRecorder
     * @return \Illuminate\Http\Response
     */
    public function show(FinanceRecorder $financeRecorder)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\FinanceRecorder  $financeRecorder
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $existing = FinanceRecorder::find($id);
        if($existing)
        {
            return view('admin.managefr.index',compact('existing'));
        }
        return "Error";
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\FinanceRecorder  $financeRecorder
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, FinanceRecorder $financeRecorder)
    {
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\FinanceRecorder  $financeRecorder
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $existing = FinanceRecorder::find($id);

        if($existing)
        {
            $existing->delete();
            return response()->json(['data'=>true]);
        }
        else
        {
            return response()->json(['data'=>false]);
        }
    }
}

app/Http/Controllers/Api/ManageFrController.php
<?php

namespace App\Http\Controllers\API;

use App\FinanceRecorder;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use App\Http\Resources\ManageFrResource;

class ManageFrController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $financeRecorders = FinanceRecorder::all();
        return response([ 'data' => ManageFrResource::collection($financeRecorders), 'message' => 'Retrieved successfully'], 200);
  
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'user_id' => 'required',
            'amount' => 'required',
            'description' => 'required'
        ]);
        
        if ($validator->fails()) {
            return response(['error' => $validator->errors(), 'Validation Error']);
        }
        
        $financeRecord = FinanceRecorder::create($data);

        return response(['financeRecord' => new ManageFrResource($financeRecord), 'message' => 'Created successfully'], 201);

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\FinanceRecorder  $financeRecorder
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $financeRecorder = FinanceRecorder::find($id);
        if (!$financeRecorder) {
            return response()->json([
                'success' => false,
                'message' => 'Record with id ' . $id . ' not found'
            ], 400);
        }
        return response(['data' => new ManageFrResource($financeRecorder), 'message' => 'Retrieved successfully'], 200);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\FinanceRecorder  $financeRecorder
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $financeRecorder = FinanceRecorder::find($id);
        if (!$financeRecorder) {
            return response()->json([
                'success' => false,
                'message' => 'Record with id ' . $id . ' not found'
            ], 400);
        }

        $financeRecorder->update($request->all());
        return response(['data' => new ManageFrResource($financeRecorder), 'message' => 'Updated successfully'], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\FinanceRecorder  $financeRecorder
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $row = FinanceRecorder::find($id);
        if (!$row) {
            return response()->json([
                'success' => false,
                'message' => 'Record with id ' . $id . ' not found'
            ], 400);
        }
        $row->delete();
        return response(['success' => true, 'message' => 'Deleted']);
    }
}

resources/views/admin/managefr/index.blade.php
@extends('layouts.admin-app')
@section('meta')
<meta name="csrf-token" content="{{ csrf_token() }}">
@stop
@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-danger">
                        <h4 class="card-title">Finance Recorder</h4>
                        <p class="card-category">Finance Recorders Information Form</p>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('managefr.store') }}">
                            @csrf
                            <div class="row">
                                <input type="hidden" value="{{ $existing == null ? old('id') : $existing->id }}"
                                    name="id">
                                <div class="col-md-4">
                                    <div
                                        class="form-group @if($errors->has('amount')) has-danger bmd-form-group @endif">
                                        <label class="bmd-label-floating">Amount</label>
                                        <input type="text" class="form-control"
                                            value="{{ $existing == null ? old('amount') : $existing->amount }}"
                                            name="amount">
                                        @if ($errors->has('amount'))
                                        <span class="form-control-feedback">
                                            <i class="material-icons">clear</i>
                                        </span>
                                        <strong style="color: red">{{ $errors->first('amount') }}</strong>
                                        @endif
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div
                                        class="form-group @if($errors->has('description')) has-danger bmd-form-group @endif">
                                        <label class="bmd-label-floating">Description</label>
                                        <textarea type="text" class="form-control"
                                            name="description">{{ $existing == null ? old('description') : $existing->description }}</textarea>
                                        @if ($errors->has('description'))
                                        <span class="form-control-feedback">
                                            <i class="material-icons">clear</i>
                                        </span>
                                        <strong style="color: red">{{ $errors->first('description') }}</strong>
                                        @endif
                                    </div>
                                </div>
                            <button type="submit" class="btn btn-danger pull-right">Save</button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-danger">
                        <h4 class="card-title ">Finance Records Information</h4>
                        <p class="card-category"> Here All Finance Records Management Available</p>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table" id="tblDetails">
                                <thead class="text-primary">
                                    <th>
                                        Amount
                                    </th>
                                    <th>
                                        Description
                                    </th>
                                    <th>
                                        Created At
                                    </th>
                                    <th>
                                        Action
                                    </th>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<div id="delete_model" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Do You Really Want to Delete This Finance Recorder</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>This Record Will be deleted Permanently</p>
            </div>
            <div class="modal-footer">
                <button type="button" id="delete_btn" class="btn btn-danger">Yes Delete It!</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="delete_id">
@endsection
@section('script')
<script>
    $(document).ready(function () {
            $('#tblDetails').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('managefr.data') }}",
                columns: [
                    {data: 'amount', name: 'amount'},
                    {data: 'description', name: 'description'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });
            $('.nav li.active').removeClass('active');
            $('#managefr').addClass('active');
        });
        function Confirm(id) {
            $('#delete_id').val(id);
            $('#delete_model').modal('show');
        }

        $('#delete_btn').click(function (e) {
           var id = $('#delete_id').val();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
               type: 'POST',
               data: {
                   _method: 'DELETE'
               },
                url:'managefr/'+id,
                success: function (data) {
                    location.reload();
                }
            });
        });
</script>
@endsection