routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);
Route::get('/', function () {
    return view('landingpage.index');
});
/*
Route::get('/', function () {
    return view('custom-auth.login');
});

Route::get('/vouchers',function () {
    return view('custom-views.voucher_master');
});*/
//Auth::routes();
Route::post('/','ContactUsController@index')->name('contact_us');

Route::group(['namespace'=>'Admin','prefix'=>'admin','as','admin.', 'middleware' => ['admin','auth']],function (){
    Route::get('/dashboard','AdminDashboardController@index')->name('dashboard');
    Route::get('/vendor-data','ManageVendorController@data')->name('vendor.data');
    Route::get('/customer-data','ManageCustomerController@data')->name('customer.data');
    Route::get('/account-data','ManageAccountController@data')->name('account.data');
    Route::get('/openingbalance-data','ManageOpeningBalanceController@data')->name('openingbalance.data');
    Route::get('/voucher-data','ManageVoucherController@data')->name('voucher.data');
    Route::post('/ledger-data','LedgerController@data')->name('ledger.data');
    Route::post('/compact-ledger-data','CompactLedgerController@data')->name('compactledger.data');



    //Route::get('/vouchers-data','ManageVoucherController@data')->name('vouchers.data');

    Route::resource('vendors','ManageVendorController');
    Route::resource('customers','ManageCustomerController');
    Route::resource('accounts','ManageAccountController');
    Route::resource('openingbalance','ManageOpeningBalanceController');
    Route::resource('vouchers','ManageVoucherController');
    Route::resource('ledgers','LedgerController');
    Route::resource('compact-ledger','CompactLedgerController');


    Route::post('saveform','ManageVoucherController@saveform')->name('save-form');
    Route::post('delete','ManageVoucherController@delete')->name('delete-data');
    Route::post('showdetail','ManageVoucherController@showdetail')->name('show-detail');

    // Finance Recorders
    Route::resource('managefr', 'ManageFrController');
    Route::get('/fr-data','ManageFrController@data')->name('managefr.data');

});

Route::get('/home', 'HomeController@index')->name('home');

resources/views/includes/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="copyright float-right">
            &copy;
            <script>
                document.write(new Date().getFullYear())
            </script>, Developed with <i class="material-icons">favorite</i> by
            <a href="#" target="_blank"> BitSoft Solutions </a> for a better Accounting Experience.
        </div>
    </div>
</footer>

resources/views/includes/nav.blade.php
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
    <div class="container-fluid">
      <div class="navbar-wrapper">
            <a class="navbar-brand" href="/admin/dashboard">Dashboard</a>
        </div>
        <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">notifications</i>
                        <span class="notification">5</span>
                        <p class="d-lg-none d-md-block">
                            Some Actions
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Mike John responded to your email</a>
                        <a class="dropdown-item" href="#">You have 5 new tasks</a>
                        <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                        <a class="dropdown-item" href="#">Another Notification</a>
                        <a class="dropdown-item" href="#">Another One</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>
                        <p class="d-lg-none d-md-block">
                            Account
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}</a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- End Navbar -->

resources/views/includes/sidebar.blade.php
<div class="sidebar" data-color="danger" data-background-color="white"
    data-image="{{ url('assets/img/sidebar-1.jpg') }}">
    <!--
      Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

      Tip 2: you can also add an image using data-image tag
  -->

    <div class="logo">
        <a href="/admin/dashboard" class="simple-text logo-normal">
            Account Manager
        </a>
    </div>
    <div class="sidebar-wrapper">
        <ul class="nav">
            <li class="nav-item active">
                <a class="nav-link" href="/admin/dashboard">
                    <i class="material-icons">dashboard</i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li class="nav-item" id="vendors">
                <a class="nav-link" href="{{ route('vendors.index') }}">
                    <i class="material-icons">person</i>
                    <p>Vendors</p>
                </a>
            </li>
            <li class="nav-item" id="customers">
                <a class="nav-link" href="{{ route('customers.index') }}">
                    <i class="material-icons">person</i>
                    <p>Customers</p>
                </a>
            </li>
            <li class="nav-item" id="accounts">
                <a class="nav-link" href="{{ route('accounts.index') }}">
                    <i class="material-icons">store</i>
                    <p>Chart Of Account</p>
                </a>
            </li>
            <li class="nav-item" id="managefr">
            <a class="nav-link set-nav-links" href="{{ route('managefr.index') }}">
                <i class="material-icons set-material-icon">store</i>
                <p>Finance Recorder</p>
            </a>
        </li>
            <li class="nav-item" id="openingbalance">
                <a class="nav-link" href="{{ route('openingbalance.index') }}">
                    <i class="material-icons">money</i>
                    <p>Opening Balance</p>
                </a>
            </li>
            <li class="nav-item" id="voucher">
                <a class="nav-link" href="{{ route('vouchers.index') }}">
                    <i class="material-icons">store</i>
                    <p>Vouchers</p>
                </a>
            </li>
            <li class="nav-item" id="ledger">
                <a class="nav-link" href="{{ route('ledgers.index') }}">
                    <i class="material-icons">money</i>
                    <p>Ledgers</p>
                </a>
            </li>
            <li class="nav-item" id="compact_ledger">
                <a class="nav-link set-nav-links" href="{{ route('compact-ledger.index') }}">
                    <i class="material-icons set-material-icon">money</i>
                    <p>Compact Ledger</p>
                </a>
            </li>
        </ul>
    </div>
</div>

<!-- side menu responsive toggle //Responsive Slide Toggle Menu// -->
<div id="mySidebar" class="set-sidebar">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
    <div class="logo set-logo">
        <a href="/admin/dashboard" class="simple-text logo-normal">
            Account Manager
        </a>
    </div>
    <hr>
    <ul class="nav set-nav-responsive" data-color="danger">
        <li class="nav-item active">
            <a class="nav-link set-nav-links" href="/admin/dashboard">
                <i class="material-icons set-material-icon">dashboard</i>
                <p>Dashboard</p>
            </a>
        </li>
        <li class="nav-item" id="vendors">
            <a class="nav-link set-nav-links" href="{{ route('vendors.index') }}">
                <i class="material-icons set-material-icon">person</i>
                <p>Vendors</p>
            </a>
        </li>
        <li class="nav-item" id="customers">
            <a class="nav-link set-nav-links" href="{{ route('customers.index') }}">
                <i class="material-icons set-material-icon">person</i>
                <p>Customers</p>
            </a>
        </li>
        <li class="nav-item" id="accounts">
            <a class="nav-link set-nav-links" href="{{ route('accounts.index') }}">
                <i class="material-icons set-material-icon">store</i>
                <p>Chart Of Account</p>
            </a>
        </li>
        <li class="nav-item" id="managefr">
            <a class="nav-link set-nav-links" href="{{ route('managefr.index') }}">
                <i class="material-icons set-material-icon">store</i>
                <p>Finance Recorder</p>
            </a>
        </li>
        <li class="nav-item" id="openingbalance">
            <a class="nav-link set-nav-links" href="{{ route('openingbalance.index') }}">
                <i class="material-icons set-material-icon">money</i>
                <p>Opening Balance</p>
            </a>
        </li>
        <li class="nav-item" id="voucher">
            <a class="nav-link set-nav-links" href="{{ route('vouchers.index') }}">
                <i class="material-icons set-material-icon">store</i>
                <p>Vouchers</p>
            </a>
        </li>
        <li class="nav-item" id="ledger">
            <a class="nav-link set-nav-links" href="{{ route('ledgers.index') }}">
                <i class="material-icons set-material-icon">money</i>
                <p>Ledgers</p>
            </a>
        </li>
        <li class="nav-item" id="compact_ledger">
            <a class="nav-link set-nav-links" href="{{ route('compact-ledger.index') }}">
                <i class="material-icons set-material-icon">money</i>
                <p>Compact Ledger</p>
            </a>
        </li>
    </ul>
</div>

<div id="main">
    <button class="openbtn" onclick="openNav()">☰</button>
</div>